data_ingestion:
    bucket_name: "recomendation_project"
    bucket_file_names:
        - "anime.csv"
        - "anime_with_synopsis.csv"
        - "animelist.csv"

model:
  embedding: 128
  loss: binary_crossentropy
  optimizer: Adam
  metrics: ['mae','mse']
